### ISSUE TITLE
留言板 | Fayne's Blog

### ISSUE THREAD

**Issue by fanjinhao** [fanjinhao/fanjinhao.github.io#22]
http://www.fayne.cn/board/

**Comment by fanjinhao** [comment]
test gitment

**Comment by fanjinhao** [comment]
```cpp
#include <stdio.h>

int main()
{
    printf("Hello Gitment");
    return 0;
}
```

```java
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello Gitment");
    }
}
```

**Comment by tl-Tangliang** [comment]
你好 ，我最近也在搭建这个博客，请问一下你左上角字体怎么设置的，还有下面的版权怎么居中的

**Comment by fanjinhao** [comment]
themes\next\source\css\_custom\custom.styl, 在这里自定义样式就好，在chrome中右键审查元素，找到id，然后重新配置css属性即可，这里改动容易复原，若是不想要这个样式直接删除就好了

**Comment by fanjinhao** [comment]
例如我的：themes\next\source\css\_custom\custom.styl
```css
// Custom styles.
.post-body p a {
  color: #0593d3;
  border-bottom: none;
  &:hover {
    color: #0477ab;
    text-decoration: underline;
  }
}
// Custom styles. //首页文章阴影样式
.post {
  margin-top: 60px;
  margin-bottom: 60px;
  padding: 25px;
  -webkit-box-shadow: 0 0 14px rgba(202, 203, 203, .5);
  -moz-box-shadow: 0 0 14px rgba(202, 203, 204, .5);
}

.site-meta .site-title {
    font-size: 24px;
    font-family: 'Comic Sans MS', sans-serif;
    color: #555555;
}
.posts-expand .post-title, .posts-expand .post-meta {
    text-align: center;
}

//首页阅读全文样式
.post-button {
    margin-top: 30px;
    text-align: center;
}
/*.post-button .btn {
    color: #f5f5f5;
    font-size: 15px;
    background: #686868;
    border-radius: 16px;
    line-height: 2;
    margin: 0 4px 8px 4px;
    padding: 0px 20px;
}*/
.post-button a{
  border-bottom: 0px solid #666;
}
.post-button .btn{
  display: inline-block;
  padding: 0 15px;
  color: #040404;
  border: 1px solid #1200bb;
  border-radius: 4px;
}
.post-button .btn:hover {
    background: #fc6423;
    color: white;
    display: inline-block;
    border: 1px solid #fc6423;
    border-radius: 4px;
}
//首页图片居中
.posts-expand .post-body img {
    margin: 0 auto;
}


//侧边栏信息样式修改
.site-author-name {
    margin: 48px 0 0;
    /*color: #090909;*/
    font-family: 'Comic Sans MS', sans-serif;
}


//侧栏按钮样式
.sidebar-toggle {
    background: #222;
}
.back-to-top {
    background: #222;
}
.page-post-detail .sidebar-toggle-line {
    background: white;
}

```
